const $=id=>document.getElementById(id);
const sources={
  miqat:['Sahih al-Bukhari 1524 · Miqat','https://sunnah.com/bukhari:1524'],
  perfume:['Sahih al-Bukhari 1539 · Wangian sebelum ihram','https://sunnah.com/bukhari:1539'],
  clothes:['Sahih al-Bukhari 1542 · Pakaian ihram lelaki','https://sunnah.com/bukhari:1542'],
  jabir:['Sahih Muslim 1218a · Hadis Jabir tentang manasik','https://sunnah.com/muslim:1218a'],
  mosque:['Sahih Muslim 713a · Doa masuk masjid','https://sunnah.com/muslim:713a'],
  takbir:['Sahih al-Bukhari 1613 · Isyarat dan takbir','https://sunnah.com/bukhari:1613'],
  dua:['Sunan Abi Dawud 1892 · Doa antara dua rukun (hasan)','https://sunnah.com/abudawud:1892'],
  shave:['Sahih al-Bukhari 1727 · Bercukur dan memendekkan rambut','https://sunnah.com/bukhari:1727'],
  intention:['Mufti Wilayah · Niat ihram','https://www.muftiwp.gov.my/en/artikel/al-kafi-li-al-fatawi/2661-al-kafi-844-niat-ihram-di-rumah-sendiri'],
  idtiba:['Mufti Wilayah · Idtiba’ dan ramal','https://www.muftiwp.gov.my/en/artikel/bayan-li-al-haj/695-bayan-li-al-haj-siri-ke-26-hukum-idhthiba-dan-definisinya'],
  wudu:['Mufti Wilayah · Wuduk ketika tawaf','https://www.muftiwp.gov.my/ms/artikel/al-kafi-li-al-fatawi/1331-al-kafi-421-bersentuhan-'],
  jawhar:['JAWHAR · Panduan haji dan umrah','https://www.jawhar.gov.my/haji-dan-umrah/panduan-haji-dan-umrah/'],
  description:['Syeikh Ibn Baz · Tatacara umrah','https://binbaz.org.sa/fatwas/11982/صفة-العمرة'],
  saudi:['Kementerian Haji dan Umrah Saudi · Panduan umrah','https://haj.gov.sa/-/media/Project/HAJJ/Awareness-Guides/UMRAH-VISIT-GUIDE/English/EN-Umrah-visit-Guide.pdf']
};
const links=(...keys)=>`<p class="source-link">${keys.map(k=>`<a href="${sources[k][1]}" target="_blank" rel="noopener noreferrer">${sources[k][0]} ↗</a>`).join('<br>')}</p>`;
const chapters=[
{
 name:'Kuala Lumpur',place:'KUL · MALAYSIA',image:'departure',eyebrow:'BERMULA DENGAN NIAT YANG IKHLAS',title:'Dari Kuala Lumpur,<br><em>menuju Baitullah.</em>',description:'Langkah seorang jemaah lelaki. Dari persiapan di tanah air, menuju ibadah umrah yang berpandukan sunnah.',note:'Memakai kain ihram belum bermakna sudah berniat ihram.',next:'Mulakan perjalanan',kicker:'SEBELUM BERANGKAT',feature:'Siapkan diri.<br>Tenangkan hati.',featureText:'Mandi, bersihkan diri dan sediakan pakaian ihram sebelum penerbangan.',featureLink:'Lihat persiapan',guideTitle:'Persiapan di Kuala Lumpur',guide:`<p>Perjalanan ini mengikuti laluan <strong>KL → Jeddah → Makkah</strong>. Siapkan keperluan perjalanan dan pelajari urutan umrah sebelum berangkat.</p><ul><li><strong>Sunat:</strong> mandi sebelum berihram. Jika perlu, potong kuku dan kemaskan rambut sebelum masuk ihram.</li><li>Lelaki memakai kain bawah dan kain atas, serta sandal yang sesuai. Tutup kedua-dua bahu pada peringkat ini.</li><li>Boleh memakai wangian pada badan sebelum berniat ihram; jangan mewangikan kain ihram.</li><li>Boleh siap memakai kain di rumah atau KLIA. Niat masuk ibadah umrah dilakukan sebelum melintasi miqat.</li></ul><p class="content-note">Niat mahu pergi umrah berbeza daripada niat memasuki ibadah umrah. Larangan ihram bermula selepas niat yang kedua.</p>${links('perfume','clothes','intention','jabir')}`
},
{
 name:'Miqat',place:'DALAM PENERBANGAN · SEBELUM MIQAT',image:'flight',eyebrow:'MENYAHUT PANGGILAN-NYA',title:'Labbaik,<br><em>Allahumma labbaik.</em>',description:'Di dalam pesawat, sebelum melintasi miqat, beliau berniat memasuki ibadah umrah. Talbiah mengiringi perjalanan ke Tanah Suci.',note:'Jangan tunggu mendarat di Jeddah untuk berniat ihram.',next:'Tiba di Makkah',kicker:'BERMULANYA IHRAM',feature:'Niat di hati.<br>Talbiah di bibir.',featureText:'Miqat bergantung pada laluan sebenar pesawat. Dapatkan maklumat daripada kru atau pembimbing lebih awal.',featureLink:'Niat & bacaan talbiah',guideTitle:'Ihram sebelum melintasi miqat',guide:`<p><strong>Wajib:</strong> bagi orang yang datang untuk umrah, jangan melepasi miqat tanpa ihram. Pastikan kain sudah dipakai dan berniat sebelum pesawat melintasi sempadannya; boleh berniat lebih awal untuk mengelakkan terlepas.</p><p>Niat di dalam hati untuk memasuki ibadah umrah. Ucapkan:</p><div class="arabic" lang="ar">لَبَّيْكَ اللَّهُمَّ عُمْرَةً<small lang="ms">Labbaika Allahumma ‘umrah — Aku menyahut panggilan-Mu, ya Allah, untuk umrah.</small></div><h3>Perbanyak talbiah</h3><div class="arabic" lang="ar">لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ<small lang="ms">Labbaik Allahumma labbaik. Labbaika la syarika laka labbaik. Innal-hamda wan-ni‘mata laka wal-mulk. La syarika lak.</small></div><p>Lelaki disunatkan mengangkat suara ketika bertalbiah dengan mengambil kira keadaan sekeliling. Teruskan sepanjang perjalanan hingga mula tawaf.</p><p class="content-note">Jika ke Madinah dahulu, panduan miqatnya berbeza: berihram di Zulhulaifah (Bir Ali) ketika menuju Makkah.</p>${links('miqat','description','jabir')}`
},
{
 name:'Makkah',place:'MAKKAH · MASJID AL-HARAM',image:'arrival',eyebrow:'DI HADAPAN BAITULLAH',title:'Langkah diperlahankan.<br><em>Hati dihadapkan.</em>',description:'Selepas mendarat di Jeddah, perjalanan diteruskan ke Makkah. Beliau masuk ke Masjid al-Haram dengan tenang, masih dalam keadaan ihram.',note:'Boleh berehat dahulu di penginapan; larangan ihram tetap dijaga.',next:'Mulakan tawaf',kicker:'MASUK KE MASJID',feature:'Memohon<br>pintu rahmat.',featureText:'Allahumma-ftah li abwaba rahmatik. Ya Allah, bukakanlah untukku pintu-pintu rahmat-Mu.',featureLink:'Adab masuk & persiapan',guideTitle:'Tiba di Masjid al-Haram',guide:`<p>Selepas urusan ketibaan di Jeddah, teruskan perjalanan ke Makkah. Ambil masa untuk berehat jika perlu, sambil menjaga larangan ihram.</p><ul><li>Masuk masjid dengan kaki kanan dan baca doa masuk masjid.</li><li>Berwuduk, pastikan badan serta pakaian suci dan aurat terjaga sebelum tawaf. Ini menepati panduan mazhab Syafi‘i.</li><li>Menuju kawasan tawaf dengan tertib. Berhenti bertalbiah apabila hendak memulakan tawaf.</li></ul><div class="arabic" lang="ar">اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ<small lang="ms">Ya Allah, bukakanlah untukku pintu-pintu rahmat-Mu.</small></div><p class="content-note">Ruang tawaf dikongsi ramai jemaah. Beri laluan dan elakkan menolak untuk mendekati Kaabah.</p>${links('mosque','wudu','description')}`
},
{
 name:'Tawaf',place:'MASJID AL-HARAM · MENGELILINGI KAABAH',image:'arrival',eyebrow:'TUJUH PUSINGAN, SATU ARAH',title:'Mengelilingi Kaabah.<br><em>Mengingati Allah.</em>',description:'Beliau bermula sejajar Hajar Aswad, dengan Kaabah di sebelah kiri. Tujuh pusingan dilakukan berlawanan arah jam.',note:'Idtiba’ ketika tawaf umrah sahaja. Tutup kembali bahu kanan selepas tawaf.',next:'Selepas tawaf',type:'tawaf',guideTitle:'Tawaf: tujuh pusingan',guide:`<ul><li><strong>Rukun:</strong> lengkapkan tujuh pusingan, bermula dan berakhir sejajar Hajar Aswad. Kaabah di sebelah kiri; laluan mesti di luar Hijr Ismail.</li><li>Apabila sejajar Hajar Aswad, bertakbir. Jika tidak dapat menyentuhnya tanpa menyakiti orang, memadai isyarat tangan; jangan berebut.</li><li><strong>Sunat bagi lelaki:</strong> idtiba’ (bahu kanan terbuka) sepanjang tawaf umrah; ramal (berjalan cepat dengan langkah pendek) pada tiga pusingan pertama apabila ruang mengizinkan. Empat selebihnya berjalan biasa.</li><li>Berzikir dan berdoa. Tiada doa khusus yang wajib bagi setiap nombor pusingan.</li></ul><h3>Antara Rukun Yamani dan Hajar Aswad</h3><div class="arabic" lang="ar">رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ<small lang="ms">Wahai Tuhan kami, berilah kebaikan di dunia dan akhirat, serta peliharalah kami daripada azab neraka.</small></div><p class="content-note">Ramal dan idtiba’ ialah sunat. Jangan menyakiti jemaah demi melakukannya.</p>${links('jawhar','takbir','idtiba','dua')}`
},
{
 name:'Solat & Zamzam',place:'MASJID AL-HARAM · SELEPAS TAWAF',image:'arrival',eyebrow:'RUANG UNTUK BERSYUKUR',title:'Dua rakaat.<br><em>Seteguk Zamzam.</em>',description:'Selesai tawaf, beliau menutup kembali bahu kanan, menunaikan dua rakaat dan minum air Zamzam sebelum menuju Safa.',note:'Solat di tempat yang sesuai. Jangan menghalang laluan orang bertawaf.',next:'Menuju Safa',kicker:'AMALAN SUNAT',feature:'Al-Kafirun.<br>Al-Ikhlas.',featureText:'Dibaca selepas al-Fatihah pada rakaat pertama dan kedua solat sunat tawaf.',featureLink:'Panduan selepas tawaf',guideTitle:'Solat selepas tawaf & Zamzam',guide:`<ul><li>Tutup semula bahu kanan selepas tawaf.</li><li>Tunaikan solat sunat tawaf dua rakaat di belakang Maqam Ibrahim jika mudah dan tidak mengganggu laluan. Jika sesak, solat di tempat lain yang sesuai dalam masjid.</li><li>Disunatkan membaca al-Kafirun selepas al-Fatihah pada rakaat pertama, dan al-Ikhlas pada rakaat kedua.</li><li>Minum air Zamzam, kemudian menuju Safa untuk sa‘i.</li></ul><p class="content-note">Maqam Ibrahim bukan tempat untuk disentuh atau digosok sebagai sebahagian manasik. Utamakan ketenangan dan ruang jemaah lain.</p>${links('jabir','description','idtiba')}`
},
{
 name:'Sa‘i',place:'SAFA ↔ MARWAH · TUJUH PERJALANAN',image:'arrival',eyebrow:'MELANGKAH DENGAN PENGHARAPAN',title:'Dari Safa,<br><em>hingga Marwah.</em>',description:'Sa‘i bermula di Safa. Pergi ke Marwah dikira satu, kembali ke Safa dikira dua. Perjalanan ketujuh berakhir di Marwah.',note:'Lelaki berlari anak di antara dua tanda hijau jika mampu dan keadaan mengizinkan.',next:'Menuju tahallul',type:'sai',guideTitle:'Sa‘i: Safa ke Marwah',guide:`<p><strong>Rukun:</strong> lakukan tujuh perjalanan selepas tawaf, bermula di Safa dan berakhir di Marwah.</p><ul><li>Ketika menghampiri Safa pada permulaan, baca ayat al-Baqarah 2:158, kemudian: <em>Abda’u bima bada’allahu bih</em> — Aku bermula dengan apa yang Allah mulakan.</li><li>Di Safa, hadap kiblat, bertakbir dan baca zikir tauhid di bawah. Ulang zikir tiga kali dengan doa di antaranya. Lakukan juga di Marwah.</li><li>Berjalan menuju Marwah. Lelaki berlari anak hanya di antara tanda hijau apabila mampu dan selamat.</li><li>Safa → Marwah = satu perjalanan; Marwah → Safa = dua. Lengkapkan tujuh.</li></ul><div class="arabic" lang="ar">لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ، أَنْجَزَ وَعْدَهُ، وَنَصَرَ عَبْدَهُ، وَهَزَمَ الْأَحْزَابَ وَحْدَهُ<small lang="ms">Tiada tuhan selain Allah, tiada sekutu bagi-Nya. Milik-Nya kerajaan dan pujian. Dia Maha Berkuasa atas segala sesuatu. Dia menunaikan janji-Nya, menolong hamba-Nya dan mengalahkan pasukan bersekutu sendirian.</small></div>${links('jabir','saudi','description')}`
},
{
 name:'Tahallul',place:'MAKKAH · SELEPAS SA‘I',image:'arrival',eyebrow:'MENYEMPURNAKAN IBADAH',title:'Rambut dicukur.<br><em>Umrah disempurnakan.</em>',description:'Selepas sa‘i, beliau mencukur rambut kepala. Dengan tahallul, selesailah umrah dan berakhirlah larangan ihram.',note:'Jangan menukar kepada pakaian biasa sebelum menyempurnakan tahallul.',next:'Selesai umrah',kicker:'TAHALLUL BAGI LELAKI',feature:'Bercukur<br>lebih utama.',featureText:'Boleh juga memendekkan rambut. Memendekkannya secara menyeluruh mengelakkan khilaf tentang kadar minimum.',featureLink:'Panduan tahallul',guideTitle:'Bercukur atau memendekkan rambut',guide:`<p>Selepas lengkap sa‘i, lakukan tahallul dengan mencukur atau memendekkan rambut kepala.</p><ul><li><strong>Bagi lelaki, bercukur lebih utama.</strong> Nabi ﷺ mendoakan mereka yang bercukur, kemudian mereka yang memendekkan rambut.</li><li>Jika memilih bergunting, pendekkan rambut secara menyeluruh. Ulama berbeza tentang kadar minimum; cara ini keluar daripada khilaf tersebut.</li><li>Setelah tahallul selesai, larangan ihram berakhir dan pakaian biasa boleh dipakai semula.</li></ul><p class="content-note">Gambaran latar menunjukkan ketibaan sebelum tahallul. Dalam urutan ibadah, cukur atau gunting dilakukan selepas selesai sa‘i.</p>${links('shave','saudi','jawhar')}`
},
{
 name:'Selesai',place:'MAKKAH · UMRAH SELESAI',image:'arrival',eyebrow:'ALHAMDULILLAH',title:'Perjalanan selesai.<br><em>Pengabdian diteruskan.</em>',description:'Ihram, tawaf, sa‘i dan tahallul telah disempurnakan. Semoga Allah menerima ibadah dan mengurniakan istiqamah selepas pulang.',note:'Ini perjalanan pembelajaran. Kiraan simulasi tidak mewakili pelaksanaan ibadah sebenar.',next:'Ulang perjalanan',kicker:'URUTAN UMRAH',feature:'Ihram → Tawaf<br>Sa‘i → Tahallul',featureText:'Jaga solat, perbanyak doa dan teruskan amal yang baik sepanjang berada di Tanah Suci.',featureLink:'Lihat semula panduan',guideTitle:'Selesai umrah',guide:`<p>Urutan umrah dalam perjalanan ini ialah <strong>niat ihram → tawaf → sa‘i → bercukur atau bergunting</strong>, dengan tertib.</p><p>Solat dua rakaat selepas tawaf, talbiah, ramal dan zikir ialah amalan yang melengkapkan pengalaman manasik dengan sunnah; kedudukannya tidak semuanya sama dengan rukun.</p><p>Selepas tahallul, bolehlah mandi dan memakai semula pakaian biasa. Teruskan menjaga solat, berdoa dan berbuat baik.</p><p class="content-note">Panduan ini memfokuskan jemaah lelaki melalui KL–Jeddah–Makkah. Untuk situasi khusus seperti terlupa niat di miqat, keuzuran atau kesilapan manasik, rujuk pembimbing yang berkelayakan.</p>${links('jawhar','saudi')}`
}
];
let current=0,activeBg=0,currentImage='',frame=0,runId=0;
const counts={tawaf:0,sai:0};
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const timeline=$('timeline'),dialog=$('guide-dialog');
timeline.innerHTML=chapters.map((s,i)=>`<button data-step="${i}" aria-label="Bab ${i+1}: ${s.name}"><span class="step-index">${String(i+1).padStart(2,'0')}</span><span class="step-name">${s.name}</span></button>`).join('');
function showBackground(name){if(name===currentImage)return;currentImage=name;const next=$(`backdrop-${activeBg?'a':'b'}`),old=$(`backdrop-${activeBg?'b':'a'}`);next.style.backgroundImage=`url('assets/${name}.webp')`;next.classList.add('is-visible');old.classList.remove('is-visible');activeBg=1-activeBg}
function featureHTML(c){if(c.type){const tawaf=c.type==='tawaf';return `<span class="feature-kicker">${tawaf?'FAHAMI ARAH TAWAF':'FAHAMI KIRAAN SA‘I'}</span><div class="simulation">${tawaf?`<svg viewBox="0 0 240 185" role="img" aria-label="Rajah tawaf berlawanan arah jam, mengelilingi Kaabah dari Hajar Aswad"><circle cx="110" cy="85" r="66" fill="none" stroke="#bba57666" stroke-width="1" stroke-dasharray="3 5"/><path d="M76 30l-12 4 3-12" fill="none" stroke="#ddc393"/><rect x="86" y="61" width="48" height="48" fill="#10201b" stroke="#ddc393"/><text x="110" y="88" text-anchor="middle" fill="#ddc393" font-size="10" font-family="sans-serif">KAABAH</text><path d="M94 60Q110 41 126 60" fill="none" stroke="#839580"/><circle cx="134" cy="109" r="3" fill="#ddc393"/><path d="M137 113l27 26" stroke="#ddc39366"/><text x="169" y="149" fill="#d0d6cc" font-size="10">Hajar Aswad</text><circle id="traveler" cx="156.67" cy="131.67" r="6" fill="#f1dab0" stroke="#14251c" stroke-width="3"/><text x="110" y="178" text-anchor="middle" fill="#aebdaf" font-size="11">Berlawanan arah jam</text></svg>`:`<svg viewBox="0 0 240 170" role="img" aria-label="Rajah sa‘i dari Safa ke Marwah dan kembali, berakhir di Marwah pada perjalanan ketujuh"><path d="M25 70H215" stroke="#9ba98e" stroke-width="1"/><path d="M100 70H140" stroke="#9bc395" stroke-width="4"/><circle cx="25" cy="70" r="4" fill="#ddc393"/><circle cx="215" cy="70" r="4" fill="#ddc393"/><circle id="traveler" cx="${counts.sai%2?215:25}" cy="70" r="7" fill="#f1dab0" stroke="#14251c" stroke-width="3"/><text x="25" y="103" text-anchor="middle" fill="#ddc393" font-size="13">Safa</text><text x="213" y="103" text-anchor="middle" fill="#ddc393" font-size="13">Marwah</text><text x="120" y="47" text-anchor="middle" fill="#a1c49c" font-size="10">Zon tanda hijau</text><text x="120" y="140" text-anchor="middle" fill="#bec9b8" font-size="11" id="direction-label">${counts.sai%2?'Marwah → Safa':'Safa → Marwah'}</text></svg>`}<div class="sim-controls"><span class="sim-label" id="sim-count" aria-live="polite">${counts[c.type]} / 7 ${tawaf?'pusingan':'perjalanan'}</span><button class="sim-button" id="sim-play">${counts[c.type]===7?'Ulang ↺':'Lihat langkah →'}</button></div><p class="sim-note">${tawaf?'Satu pusingan berakhir semula di Hajar Aswad.':'Satu hala dikira satu perjalanan.'} Simulasi pembelajaran.</p></div>`}return `<span class="feature-kicker">${c.kicker}</span><p class="feature-title">${c.feature}</p><div class="feature-rule"></div><p class="feature-text">${c.featureText}</p><button class="feature-link" id="feature-guide">${c.featureLink}<span aria-hidden="true">↗</span></button>`}
function navigate(index,{updateHash=true,scroll=false}={}){if(!Number.isInteger(index)||index<0||index>=chapters.length)return;cancelAnimationFrame(frame);runId++;current=index;const c=chapters[index];showBackground(c.image);$('chapter-label').textContent=`${String(index+1).padStart(2,'0')} / 08 · ${c.name.toLocaleUpperCase('ms')}`;$('eyebrow').textContent=c.eyebrow;$('scene-title').innerHTML=c.title;$('scene-description').textContent=c.description;$('scene-note').textContent=c.note;$('next').innerHTML=`${c.next}<span aria-hidden="true">${index===7?'↺':'↗'}</span>`;$('location').textContent=c.place;$('step-count').textContent=String(index+1).padStart(2,'0');$('previous').disabled=index===0;$('scene-feature').innerHTML=featureHTML(c);$('scene-feature').setAttribute('aria-label',c.type?'Simulasi '+c.name:c.kicker);if($('feature-guide'))$('feature-guide').onclick=showGuide;if($('sim-play'))$('sim-play').onclick=playSimulation;for(const b of timeline.children){const n=Number(b.dataset.step);b.classList.toggle('completed',n<index);if(n===index)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')}const copy=$('story-copy');copy.classList.remove('story-enter');void copy.offsetWidth;copy.classList.add('story-enter');if(updateHash)history.replaceState(null,'',`#bab-${index+1}`);if(scroll)window.scrollTo({top:0,behavior:reduced.matches?'instant':'smooth'});const active=timeline.children[index];timeline.scrollTo({left:active.offsetLeft-timeline.offsetLeft-12,behavior:reduced.matches?'instant':'smooth'});document.title=`${c.name} · Jejak Umrah`}
function openDialog(title,html,label='PANDUAN SUNNAH'){$('dialog-eyebrow').textContent=label;$('dialog-content').innerHTML=`<h2 id="dialog-title">${title}</h2>${html}`;if(!dialog.open)dialog.showModal();dialog.scrollTop=0}
function showGuide(){const c=chapters[current];openDialog(c.guideTitle,c.guide+`<button class="dialog-nav" id="overview-button">Ringkasan & larangan ihram ↗</button>`,`BAB ${String(current+1).padStart(2,'0')} · AMALAN & DALIL`);$('overview-button').onclick=showOverview}
function showOverview(){openDialog('Umrah, selangkah demi selangkah.',`<p>Panduan seorang jemaah lelaki melalui <strong>Kuala Lumpur → Jeddah → Makkah</strong>, berasaskan hadis dan panduan institusi agama.</p><h3>Rukun dan amalan sunat</h3><p>Dalam susunan mazhab Syafi‘i: niat ihram, tawaf, sa‘i, bercukur atau bergunting, serta tertib ialah rukun umrah. Berniat di miqat dan menjaga larangan ihram ialah perkara wajib. Amalan seperti mandi ihram, talbiah, idtiba’ dan ramal adalah sunat.</p><h3>Semasa dalam ihram</h3><ul><li>Jangan sengaja memotong rambut atau kuku, memakai wangian, melakukan hubungan suami isteri atau akad nikah, dan memburu haiwan buruan darat.</li><li>Lelaki tidak menutup kepala dengan penutup yang melekap dan tidak memakai baju, seluar atau pakaian yang dibentuk mengikut anggota. Jahitan pada kain, tali pinggang atau beg bukan semata-mata sebab larangan.</li><li>Jaga adab, percakapan dan hak jemaah lain sepanjang ibadah.</li></ul><p class="content-note">Bab-bab membezakan rukun, wajib dan sunat. Perincian khilaf diterangkan apabila berkaitan; panduan tidak menganggap hanya satu mazhab mengikuti sunnah.</p>${links('jawhar','clothes','idtiba')}`)}
function showSources(){openDialog('Rujukan perjalanan ini.',`<p>Rujukan hadis dan panduan untuk dibaca bersama penerangan setiap bab.</p><ul class="reference-list">${Object.values(sources).map(s=>`<li><a href="${s[1]}" target="_blank" rel="noopener noreferrer">${s[0]} ↗</a></li>`).join('')}</ul><p class="content-note">Ilustrasi dijana untuk penceritaan. Ia bukan foto dokumentari, peta miqat atau gambaran tepat susun atur semasa. Simulasi menerangkan arah dan kiraan sahaja.</p>`,'DALIL & PANDUAN')}
function playSimulation(){const type=chapters[current].type;if(!type)return;if(counts[type]===7){counts[type]=0;$('scene-feature').innerHTML=featureHTML(chapters[current]);$('sim-play').onclick=playSimulation;return}const marker=$('traveler'),button=$('sim-play');const token=++runId;button.disabled=true;button.textContent='Sedang bergerak…';let elapsed=0,last=performance.now();const reducedNow=reduced.matches||document.body.classList.contains('pause-motion');const duration=reducedNow?0:1600;function tick(now){if(token!==runId)return;const paused=document.body.classList.contains('pause-motion')&&!reducedNow;if(!paused)elapsed+=now-last;last=now;const p=duration?Math.min(elapsed/duration,1):1;if(type==='tawaf'){const a=Math.PI/4-2*Math.PI*p;marker.setAttribute('cx',110+66*Math.cos(a));marker.setAttribute('cy',85+66*Math.sin(a))}else{const reverse=counts.sai%2;marker.setAttribute('cx',reverse?215-190*p:25+190*p)}if(p<1){frame=requestAnimationFrame(tick);return}counts[type]++;$('sim-count').textContent=`${counts[type]} / 7 ${type==='tawaf'?'pusingan':'perjalanan'}`;button.disabled=false;button.textContent=counts[type]===7?'Ulang ↺':'Lihat langkah →';if(type==='sai')$('direction-label').textContent=counts.sai===7?'Selesai di Marwah':counts.sai%2?'Seterusnya: Marwah → Safa':'Seterusnya: Safa → Marwah'}frame=requestAnimationFrame(tick)}
timeline.onclick=e=>{const button=e.target.closest('[data-step]');if(button)navigate(Number(button.dataset.step),{scroll:true})};
$('next').onclick=()=>{if(current===7){counts.tawaf=0;counts.sai=0}navigate((current+1)%8,{scroll:true})};
$('previous').onclick=()=>navigate(current-1,{scroll:true});
$('details').onclick=showGuide;$('open-guide').onclick=showOverview;$('open-sources').onclick=showSources;$('close-dialog').onclick=()=>dialog.close();
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
$('motion').onclick=function(){const paused=document.body.classList.toggle('pause-motion');this.setAttribute('aria-pressed',String(paused));this.setAttribute('aria-label',paused?'Sambung animasi':'Jeda animasi');this.textContent=paused?'▷':'Ⅱ'};
document.querySelector('.brand').onclick=e=>{e.preventDefault();navigate(0,{scroll:true})};
document.addEventListener('keydown',e=>{if(dialog.open||e.altKey||e.ctrlKey||e.metaKey||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='ArrowRight'&&current<7){e.preventDefault();navigate(current+1,{scroll:true})}if(e.key==='ArrowLeft'&&current>0){e.preventDefault();navigate(current-1,{scroll:true})}});
window.addEventListener('hashchange',()=>{const m=location.hash.match(/^#bab-([1-8])$/);if(m)navigate(Number(m[1])-1,{updateHash:false})});
let startTouch=null;$('story-copy').addEventListener('touchstart',e=>{startTouch={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY}},{passive:true});$('story-copy').addEventListener('touchend',e=>{if(!startTouch||dialog.open)return;const dx=e.changedTouches[0].clientX-startTouch.x,dy=e.changedTouches[0].clientY-startTouch.y;if(Math.abs(dx)>80&&Math.abs(dx)>Math.abs(dy)*1.6)navigate(current+(dx<0?1:-1),{scroll:true});startTouch=null},{passive:true});
for(const n of ['departure','flight','arrival']){const image=new Image();image.src=`assets/${n}.webp`}
const initial=location.hash.match(/^#bab-([1-8])$/);navigate(initial?Number(initial[1])-1:0,{updateHash:false});
